throw
new
Exception
catch
Exception
finally
getAmount
